# Python para Análise de Dados - Exercícios

<font color=blue><b> Data Science do Zero </b></font><br>

1) Importe a biblioteca Pandas

In [2]:
import pandas as pd

2) Leia a base de dados **kc_house_data.csv** localizada no diretorio **datasets** e crie um Dataframe chamado **df**.

In [4]:
df = pd.read_csv('kc_house_data.csv')

3) Utilizando o Dataframe criado faça:
- a) Conte a quantidade de linhas.
- b) Imprima as informações do Dataframe.
- c) Imprima o nome das colunas do Dataframe.
- d) Imprima as informações estatisticas da coluna **bedrooms**.
- e) Imprima os valores únicos da coluna **bedrooms**.
- f) Imprima o valor médio da coluna **bathrooms**.

## 3) Respostas##

**a) Conte a quantidade de linhas.**

In [ ]:
df.count()

**b) Imprima as informações do Dataframe.**

In [ ]:
df.info()

**c) Imprima o nome das colunas do Dataframe.**

In [ ]:
df.columns

**d) Imprima as informações estatisticas da coluna bedrooms.**

In [6]:
df.bedrooms.describe()

count    21609.000000
mean         3.370910
std          0.930084
min          0.000000
25%          3.000000
50%          3.000000
75%          4.000000
max         33.000000
Name: bedrooms, dtype: float64

**e) Imprima os valores únicos da coluna bedrooms.**

In [7]:
df.bedrooms.unique()

array([ 3.,  2.,  4.,  5., nan,  1.,  6.,  7.,  0.,  8.,  9., 11., 10.,
       33.])

**f) Imprima o valor médio da coluna bathrooms.**

In [ ]:
df.bathrooms.mean()

4) Some a quantidade de valores nulos de cada coluna do Dataframe.

**Resposta**

In [12]:
df.isnull.count()

AttributeError: 'function' object has no attribute 'count'

5) Remova as linhas onde tenha pela menos um registro faltante em algum atributo.

**Resposta**

In [ ]:
df.dropna(inplace=True)

6) Preencha com 1 os values null da coluna bedrooms.

**Resposta**

In [ ]:
df['bedrooms'].fillna(1, inplace=True)

6) Com os seus conhecimentos em consultas faça:
- a) Retorne todos os imoveis que tenham o número de **bathrooms maior que 1**.
- b) Retorne todos os imoveis que tenham a quantidade **de bedrooms igual a 4**.
- c) Conte o retorno da consulta anterior.
- d) Ordena o Dataframe pela coluna **price** em **ordem decrescente**.
- e) Agrupe e conte quantidade de imóveis por tamanho de quartos.

**a)**

In [14]:
df.loc[(df['bathrooms']>1)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
3,2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3.0,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3.0,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
9,3793500160,20150312T000000,323000.0,3.0,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3.0,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
13,6054650070,20141007T000000,400000.0,3.0,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5.0,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4.0,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3.0,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
20,6300500875,20140514T000000,385000.0,4.0,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2524049179,20140826T000000,2000000.0,3.0,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000.0,5.0,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,8091400200,20140516T000000,252700.0,2.0,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,3814700200,20141120T000000,329000.0,3.0,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,1202000200,20141103T000000,233000.0,3.0,2.00,1710,4697,1.5,0,0,...,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,1794500383,20140626T000000,937000.0,3.0,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
28,5101402488,20140624T000000,438000.0,3.0,1.75,1520,6380,1.0,0,0,...,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,1873100390,20150302T000000,719000.0,4.0,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
30,8562750320,20141110T000000,580500.0,3.0,2.50,2320,3980,2.0,0,0,...,8,2320,0,2003,0,98027,47.5391,-122.070,2580,3980
31,2426039314,20141201T000000,280000.0,2.0,1.50,1190,1265,3.0,0,0,...,7,1190,0,2005,0,98133,47.7274,-122.357,1390,1756
32,461000390,20140624T000000,687500.0,4.0,1.75,2330,5000,1.5,0,0,...,7,1510,820,1929,0,98117,47.6823,-122.368,1460,5000
34,7955080270,20141203T000000,322500.0,4.0,2.75,2060,6659,1.0,0,0,...,7,1280,780,1981,0,98058,47.4276,-122.157,2020,8720
35,9547205180,20140613T000000,696000.0,3.0,2.50,2300,3060,1.5,0,0,...,8,1510,790,1930,2002,98115,47.6827,-122.310,1590,3264
37,2768000400,20141230T000000,640000.0,4.0,2.00,2360,6000,2.0,0,0,...,8,2360,0,1904,0,98107,47.6702,-122.362,1730,4700
39,2078500320,20140620T000000,605000.0,4.0,2.50,2620,7553,2.0,0,0,...,8,2620,0,1996,0,98056,47.5301,-122.180,2620,11884
40,5547700270,20140715T000000,625000.0,4.0,2.50,2570,5520,2.0,0,0,...,9,2570,0,2000,0,98074,47.6145,-122.027,2470,5669
41,7766200013,20140811T000000,775000.0,4.0,2.25,4220,24186,1.0,0,0,...,8,2600,1620,1984,0,98166,47.4450,-122.347,2410,30617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21580,7853420110,20141003T000000,594866.0,3.0,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
21581,7853420110,20150504T000000,625000.0,3.0,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
21582,3052700432,20141112T000000,490000.0,3.0,2.25,1500,1290,2.0,0,0,...,8,1220,280,2006,0,98117,47.6785,-122.375,1460,1375
21584,952006823,20141202T000000,380000.0,3.0,2.50,1260,900,2.0,0,0,...,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,3832050760,20140828T000000,270000.0,3.0,2.50,1870,5000,2.0,0,0,...,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,2767604724,20141015T000000,505000.0,2.0,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,6632300207,20150305T000000,385000.0,3.0,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,2767600688,20141113T000000,414500.0,2.0,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,7570050450,20140910T000000,347500.0,3.0,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,7430200100,20140514T000000,1222500.0,4.0,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,4140940150,20141002T000000,572000.0,4.0,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,1931300412,20150416T000000,475000.0,3.0,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,8672200110,20150317T000000,1088000.0,5.0,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,5087900040,20141017T000000,350000.0,4.0,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,1972201967,20141031T000000,520000.0,2.0,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,7502800100,20140813T000000,679950.0,5.0,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000.0,4.0,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800.0,4.0,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4.0,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1537000.0,5.0,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,5100403806,20150407T000000,467000.0,3.0,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,844000965,20140626T000000,224000.0,3.0,1.75,1500,11968,1.0,0,0,...,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,7852140040,20140825T000000,507250.0,3.0,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3.0,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4.0,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4.0,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3.0,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21611,291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287

**b)**

In [ ]:
df.loc[(dataset['bedrooms']==4)]

**c)**

In [ ]:
df.loc[(dataset['bedrooms']==4)].count()

**d)**

In [ ]:
df.sort_values(by='price', ascending=False)

**e)**

In [ ]:
pd.value_counts(dataset['bedrooms'])

7) Crie uma coluna que seja a soma das colunas **bathrooms** e **bedrooms** com o nome **comodos**

**Resposta**

In [16]:
df['comodos'] = (df['bathrooms']+df['bedrooms'])
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,comodos
0,7129300520,20141013T000000,221900.0,3.0,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,4.00
1,6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,5.25
2,5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,3.00
3,2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,7.00
4,1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,5.00

8) Visualize em formato de **histograma** a distribuição dos imoveis por preço.

**Resposta**

In [ ]:
%matplotlib notebook
df['price'].plot()

9) Visualize em formato disperção os imoveis utilizando as colunas **bathrooms** e **price**.

**Resposta**

In [ ]:
df.plot(x='bedrooms',y='price',kind='scatter', title='Bedrooms x Price',color='r')

10) Gere uma **planilha do Excel** a partir do Dataframe criado.

**Resposta**

In [ ]:
df.to_excel('datasets/planilha_house.xls',index=False)